version: '3'
services:
  auth:
    build:
      context: ./
      dockerfile: auth/Dockerfile
    container_name: private-auth-service
    networks:
      - auth
    depends_on:
      - auth-db
      - redis
  auth-public:
    build:
      context: ./
      dockerfile: auth-public/Dockerfile
    container_name: public-auth-service
    ports:
      - 8001:80
    networks:
      - webnet
      - auth
    depends_on:
      - auth
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    container_name: api-service
    ports: 
      - 8000:80
    networks:
      - webnet
      - api
    depends_on:
      - auth
      - api-db
      - redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - auth
      - api
  api-db:
    build: api/db
    container_name: api-pgdb
    restart: always
    networks:
      - api
  auth-db:
    build: auth/db
    container_name: auth-pgdb
    restart: always
    networks:
      - auth
  redis:
    image: redis
    container_name: session-store
    networks:
      - api
      - auth
  # frontend:
networks:
  webnet:
    driver: bridge
  auth:
    driver: bridge
  api:
    driver: bridge
  private:
    driver: bridge